### ISSUE TITLE
MOM installer for Fields of Mistra - Error

### ISSUE THREAD

**Issue by ashbashsacecat** [Garethp/Mods-of-Mistria-Installer#4]
Hi, I downloaded the new version of the MOM installer for Fields of Mistra [https://www.nexusmods.com/fieldsofmistria/mods/78?tab=description](url) and I ran into an issue I need assistance with. It's mainly for the "[More Hairstyles - Enable hidden Hairstyles](https://www.nexusmods.com/fieldsofmistria/mods/81)" mod which is making it so I cannot open my game since my character is using a hairstyle of said mod.  I've been using the old version of MOM which has worked until today when it updated. Now I'm getting that error again that I can't seem to fix. Does anyone know a workaround? :( This is the full error code I'm getting:

**Copy of error message:**

_{"message":"asset of name `spr_player_blown_out_twist_hair_mid` doesn't exist","stacktrace":
"ERROR in action number 1\nof Create Event for object Setup:\nasset of name `spr_player_blown_out_twist_hair_mid` doesn't exist"}

Outfit blown_out_twist has incorrect ui_su
b_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit medium_pigtails has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit straight_long_bun has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit straight_long_twin_buns has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit wavy_long_ponytail has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit wavy_long_twin_buns has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit wavy_medium has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit wavy_medium_fringed has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair.
Outfit wavy_medium_twin_buns has incorrect ui_sub_category. Must be one of: medium_hair, short_hair, long_hair._

**Copy of images for reference:**

![2024-10-02_00h26_01](https://github.com/user-attachments/assets/2f3fa68e-5b6c-4879-93c7-e0a6aa65632f)
![2024-10-02_00h27_01](https://github.com/user-attachments/assets/8dc44ee1-2fee-4ed5-a5f1-6bd3b6c52444)
![2024-10-02_00h27_43](https://github.com/user-attachments/assets/d2a3e649-ed95-4233-a2f5-e3cb5e3a51fd)

**Comment by Garethp** [comment]
It looks like you have an older version of MOMI. Can you download `0.3.2` and try again?
